### ISSUE TITLE
Reformatting does work on indented lines

### ISSUE THREAD

**Issue by TBail** [mhilbush/openhab-formatter#1]
I just regconnized that the plugin only reformates if lines are not indented. 

Typically, my files are structured in such a way that they have a group at the beginning that acts as a bracket for the individual items. The underlying items are then indented with a TAB, so that the whole file has a structure.

It would be great is this could be implemented

**Comment by mhilbush** [comment]
@TBail Do you want it to retain the existing whitespace, or remove it? If retained, do you want that same amount of whitespace added to the indent level of the other lines?

So, if the line is this (indented by one tab stop).
```
    Number:Temperature Temperature "Label [%.0f]" <none> (group) ["tag"] { channel="some:channel" }
```

Do you want this (no indent)?
```
Number:Temperature          Temperature
                            "Label [%.0f]"
                            <none>
                            (group)
                            ["tag"]
                            { channel="some:channel" }
```

This (first line indented by amount of initial indent)?
```
    Number:Temperature          Temperature
                            "Label [%.0f]"
                            <none>
                            (group)
                            ["tag"]
                            { channel="some:channel" }
```

Or this (all lines indented by amount of initial indent)?
```
    Number:Temperature          Temperature
                                "Label [%.0f]"
                                <none>
                                (group)
                                ["tag"]
                                { channel="some:channel" }
```

**Comment by TBail** [comment]
@mhilbush 

In my enviroemnet i would prefer option three. How about a configuration option to set option one or option 3

**Comment by mhilbush** [comment]
> How about a configuration option to set option one or option 3

Yeah, I think a `preserveWhitespace` options would do it.

I also was going to make the overall indent level configurable (currently 28 characters), so this might be a good time for me to figure out how to do configuration... LOL

**Comment by mhilbush** [comment]
@TBail 

Try version 0.0.5. The parameters are defined in the README.

**Comment by TBail** [comment]
@mhilbush 

Works like a charm!!!!

Thanks a lot
